modLoader="javafml"
loaderVersion="0"
license="${mod_license}"

[[mods]]
modId="create_ergonomic"
version="${mod_version}"
displayName="Create: Ergonomic"
authors="dong"
description='''ce'''

[[dependencies.create_ergonomic]]
modId = "forge"
mandatory = true
versionRange = "0"
ordering = "NONE"
side="BOTH"

[[dependencies.create_ergonomic]]
modId = "minecraft"
mandatory = true
versionRange = "0"
ordering = "NONE"
side="BOTH"

[[dependencies.create_ergonomic]]
modId = "create"
mandatory = true
versionRange = "[0.5,1.0)"
ordering = "NONE"
side = "BOTH"

[[dependencies.create_ergonomic]]
modId = "cloth_config"
mandatory = true
versionRange = "0"
ordering = "NONE"
side = "BOTH"
