modLoader="javafml"
loaderVersion="0"
license="${mod_license}"
issueTrackerURL = "${mod_issue_url}"

[[mods]]
modId="create_ergonomic"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''
logoFile = "icon.png"
logoBlur = false

[[mixins]]
config = "create_ergonomic.mixins.json"

[[dependencies.create_ergonomic]]
modId = "neoforge"
type = "required"
ordering = "NONE"
side="BOTH"

[[dependencies.create_ergonomic]]
modId = "minecraft"
type = "required"
ordering = "NONE"
side="BOTH"

[[dependencies.create_ergonomic]]
modId = "create"
type = "required"
ordering = "NONE"
side = "BOTH"

[[dependencies.create_ergonomic]]
modId = "cloth_config"
type = "required"
ordering = "NONE"
side = "BOTH"
